#!/usr/bin/env python

import sys
f = open('out.czl')

basename = None
cycle_period = None
inst_period = None

for line in f:
  line = line.strip()
  parts = line.split('\t')
  
  if parts[0] == 'basename':
    basename = parts[1]
  elif parts[0] == 'cycle period':
    cycle_period = int(parts[1])
  elif parts[0] == 'instruction period':
    inst_period = int(parts[1])
  elif parts[0] == 'blockstats':
    (file, fn, base_str, limit_str, length_str, cyc_str, inst_str) = parts[1:]
    length = int(length_str)
    cyc = int(cyc_str)
    inst = int(inst_str)
    base = int(base_str, 16)
    limit = int(limit_str, 16)
    
    trips = float(inst_period * inst) / length
    
    print file, fn, base_str, inst
    print "  has", length, "instructions"
    print "  executed", int(trips), "times"
